<a href="https://colab.research.google.com/github/maulsabani01-cell/Tugas-data-mining-2304020137/blob/main/tugas%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

to install library 'pandas'

In [11]:
import pandas as pd

to import 'pandas' as pd

In [3]:
from google.colab import drive

to import data from drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

to connect google drive to colab

In [27]:
path = '/content/drive/MyDrive/data.csv'

to save csv file in var 'path'

In [28]:
df = pd.read_csv(path)

In [32]:
df.head(10)

,Context,Response
0,Aku sedang melalui beberapa hal dengan perasaa...,"Jika semua orang berpikir Anda tidak berharga,..."
1,Aku sedang melalui beberapa hal dengan perasaa...,"Halo, dan terima kasih atas pertanyaan Anda d..."
2,Aku sedang melalui beberapa hal dengan perasaa...,Hal pertama yang saya sarankan adalah mendapat...
3,Aku sedang melalui beberapa hal dengan perasaa...,Terapi sangat penting bagi mereka yang merasa ...
4,Aku sedang melalui beberapa hal dengan perasaa...,Pertama-tama saya ingin memberi tahu Anda bahw...
5,Aku sedang melalui beberapa hal dengan perasaa...,"Heck, pasti, hun! Perasaan 'depresi' memili..."
6,Aku sedang melalui beberapa hal dengan perasaa...,Anda menunjukkan beberapa sifat spesifik dari ...
7,Aku sedang melalui beberapa hal dengan perasaa...,Itu intens. Depresi adalah pembohong. Terkad...
8,Aku sedang melalui beberapa hal dengan perasaa...,Sepertinya Anda mungkin menempatkan diri Anda ...
9,Aku sedang melalui beberapa hal dengan perasaa...,Pasti sangat sulit untuk mengalami apa yang An...

10 data awal

In [31]:
df.tail()

,Context,Response
5662,Apa saja kesulitan yang bisa ditemui oleh seor...,Meskipun banyak klien memiliki kapasitas untuk...
5663,Apa saja kesulitan yang bisa ditemui oleh seor...,Saya biasanya tidak memberi label klien sebaga...
5664,Apa saja kesulitan yang bisa ditemui oleh seor...,"Sial! Heh heh, dan perbaiki saya jika saya sa..."
5665,Apa saja kesulitan yang bisa ditemui oleh seor...,"Ya, seperti beberapa hubungan di luar pekerja..."
5666,Apa saja kesulitan yang bisa ditemui oleh seor...,"Setiap konselor akan memiliki daftar ""kesulita..."

5 data terakhir

In [33]:
df.loc[2]

Context     Aku sedang melalui beberapa hal dengan perasaa...
Response    Hal pertama yang saya sarankan adalah mendapat...
Name: 2, dtype: object

untuk mengakses kolom berdasarkan yang kalian inginkan

In [38]:
df.iloc[1:100]

,Context,Response
1,Aku sedang melalui beberapa hal dengan perasaa...,"Halo, dan terima kasih atas pertanyaan Anda d..."
2,Aku sedang melalui beberapa hal dengan perasaa...,Hal pertama yang saya sarankan adalah mendapat...
3,Aku sedang melalui beberapa hal dengan perasaa...,Terapi sangat penting bagi mereka yang merasa ...
4,Aku sedang melalui beberapa hal dengan perasaa...,Pertama-tama saya ingin memberi tahu Anda bahw...
5,Aku sedang melalui beberapa hal dengan perasaa...,"Heck, pasti, hun! Perasaan 'depresi' memili..."
...,...,...
95,Saya berjuang dengan depresi serta perubahan s...,Sangat menyenangkan untuk mengendarai roller c...
96,Saya berjuang dengan depresi serta perubahan s...,Apakah Anda yakin tertinggi dan terendah Anda ...
97,Saya berjuang dengan depresi serta perubahan s...,Gejala depresi dan PMS bisa sangat sulit dinav...
98,Saya berjuang dengan depresi serta perubahan s...,Anda mungkin sudah menjalani kehidupan yang se...
99,"Saya melukai diri sendiri, dan saya berhenti ...","Di satu sisi, melukai diri sendiri dapat meny..."

memilih baris dari indeks tertentu sampai tertentu

In [37]:
df['Context'] [1:10]

1    Aku sedang melalui beberapa hal dengan perasaa...
2    Aku sedang melalui beberapa hal dengan perasaa...
3    Aku sedang melalui beberapa hal dengan perasaa...
4    Aku sedang melalui beberapa hal dengan perasaa...
5    Aku sedang melalui beberapa hal dengan perasaa...
6    Aku sedang melalui beberapa hal dengan perasaa...
7    Aku sedang melalui beberapa hal dengan perasaa...
8    Aku sedang melalui beberapa hal dengan perasaa...
9    Aku sedang melalui beberapa hal dengan perasaa...
Name: Context, dtype: object

menampilkan nilai dari kolom yang kalian inginkan beserta mau berapa